# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- powershell: npm install
  displayName: 'npm install'

- task: VSTest@2
  inputs:
    testSelector: 'testPlan'
    testPlan: '1'
    testSuite: '2'
    testConfiguration: '2'
    searchFolder: '$(System.DefaultWorkingDirectory)'
    vsTestVersion: '16.0'

# - task: VSTest@2
#   inputs:
#     testSelector: testAssemblies
#     testAssemblyVer2: '**\\tests\\**'

# - powershell: node_modules\.bin\jest
#   displayName: 'jest test'

# - task: PublishTestResults@2
#   displayName: 'Publish Test Results'
#   inputs:
#     testResultsFiles: quality/junit.xml
#     testRunTitle: test results
#   condition: succeededOrFailed()

# - publish: $(System.DefaultWorkingDirectory)/test-results.json
#   artifact: test-results.json
#   condition: succeededOrFailed()
#   displayName: Publish JSON test results